### ISSUE TITLE
Tracking supported version of related (KIC, Gateway) images.

### ISSUE THREAD

**Issue by jrsmroz** [Kong/gateway-operator#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Add ability to track supported version of KIC and Gateway versions.
The Red Hat bundle or operator hub bundle may use different base images (distroless, Red Hat UBI based), but ideally they should pull the same version of related images.
Propose of this issue is to think about a way how to track those version globally.

### Acceptance Criteria

- [ ] As a developer I don't need to track version of supperted related images separately for operator hub, RedHat certified bundle, Red Hat marketplace bundle or raw deployment.
- [ ] As a developer I can change currently supported version of a related image in one place.
